In [1]:
# Load the data
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

data = pd.read_excel(r"C:\Users\KUSHMA\Downloads\Assignemnent Questions\Online retail.xlsx", header=None)
data.head()

                                                   0
0  shrimp,almonds,avocado,vegetables mix,green gr...
1                             burgers,meatballs,eggs
2                                            chutney
3                                     turkey,avocado
4  mineral water,milk,energy bar,whole wheat rice...

In [2]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7501 entries, 0 to 7500
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       7501 non-null   object
dtypes: object(1)
memory usage: 58.7+ KB

In [3]:
data.isnull().sum()

0    0
dtype: int64

In [4]:
data.describe()

              0
count      7501
unique     5176
top     cookies
freq        223

In [5]:
data.columns = ['Transactions']

In [6]:
# Split the transactions into a list of items
data['Transactions'] = data['Transactions'].apply(lambda x: x.split(','))

In [7]:
# Import necessary libraries
from mlxtend.preprocessing import TransactionEncoder
import pandas as pd

# Convert transactions into the required format using TransactionEncoder
te = TransactionEncoder()

# Fit and transform the 'Transactions' column
te_ary = te.fit_transform(data['Transactions'])

# Create a DataFrame from the transformed array
df = pd.DataFrame(te_ary, columns=te.columns_)

# Display the resulting DataFrame
df

,asparagus,almonds,antioxydant juice,asparagus,avocado,babies food,bacon,barbecue sauce,black tea,blueberries,...,turkey,vegetables mix,water spray,white wine,whole weat flour,whole wheat pasta,whole wheat rice,yams,yogurt cake,zucchini
0,False,True,True,False,True,False,False,False,False,False,...,False,True,False,False,True,False,False,True,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,True,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7496,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7497,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7498,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7499,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7500,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False

In [8]:
# Apply the Apriori algorithm
frequent_itemsets = apriori(df, min_support=0.01, use_colnames=True)
frequent_itemsets

      support                                 itemsets
0    0.020397                                (almonds)
1    0.033329                                (avocado)
2    0.010799                         (barbecue sauce)
3    0.014265                              (black tea)
4    0.011465                             (body spray)
..        ...                                      ...
252  0.011065       (mineral water, milk, ground beef)
253  0.017064  (mineral water, spaghetti, ground beef)
254  0.015731         (mineral water, spaghetti, milk)
255  0.010265    (mineral water, olive oil, spaghetti)
256  0.011465     (pancakes, mineral water, spaghetti)

[257 rows x 2 columns]

In [9]:
# Generate the association rules
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1)

# Display the rules
print(rules.head())

       antecedents      consequents  antecedent support  consequent support  \
0  (mineral water)        (avocado)            0.238368            0.033329
1        (avocado)  (mineral water)            0.033329            0.238368
2        (burgers)           (cake)            0.087188            0.081056
3           (cake)        (burgers)            0.081056            0.087188
4        (burgers)      (chocolate)            0.087188            0.163845

    support  confidence      lift  leverage  conviction  zhangs_metric
0  0.011598    0.048658  1.459926  0.003654    1.016113       0.413630
1  0.011598    0.348000  1.459926  0.003654    1.168147       0.325896
2  0.011465    0.131498  1.622319  0.004398    1.058080       0.420238
3  0.011465    0.141447  1.622319  0.004398    1.063198       0.417434
4  0.017064    0.195719  1.194537  0.002779    1.039630       0.178411

In [10]:
# Display the rules
print("Top 5 rules based on lift:")
print(rules.nlargest(5, 'lift'))

# Sort the rules by confidence and display the top 5
print("\nTop 5 rules based on confidence:")
print(rules.nlargest(5, 'confidence'))

# Sort the rules by support and display the top 5
print("\nTop 5 rules based on support:")
print(rules.nlargest(5, 'support'))

# Further analysis to interpret the results
# Identify frequent antecedents and consequents
frequent_antecedents = rules['antecedents'].value_counts().head()
frequent_consequents = rules['consequents'].value_counts().head()

print("\nMost frequent antecedents:")
print(frequent_antecedents)

print("\nMost frequent consequents:")
print(frequent_consequents)

# Example of interpreting a rule
example_rule = rules.iloc[0]
antecedents = list(example_rule['antecedents'])
consequents = list(example_rule['consequents'])
confidence = example_rule['confidence']
lift = example_rule['lift']

print(f"\nExample Rule Interpretation:\nIf a customer buys {antecedents}, they are likely to buy {consequents} as well.")
print(f"Confidence: {confidence}, Lift: {lift}")

Top 5 rules based on lift:
                    antecedents                 consequents  \
214             (herb & pepper)               (ground beef)
215               (ground beef)             (herb & pepper)
382  (mineral water, spaghetti)               (ground beef)
387               (ground beef)  (mineral water, spaghetti)
395  (mineral water, spaghetti)                 (olive oil)

     antecedent support  consequent support   support  confidence      lift  \
214            0.049460            0.098254  0.015998    0.323450  3.291994
215            0.098254            0.049460  0.015998    0.162822  3.291994
382            0.059725            0.098254  0.017064    0.285714  2.907928
387            0.098254            0.059725  0.017064    0.173677  2.907928
395            0.059725            0.065858  0.010265    0.171875  2.609786

     leverage  conviction  zhangs_metric
214  0.011138    1.332860       0.732460
215  0.011138    1.135410       0.772094
382  0.011196    1.262445       0.697788
387  0.011196    1.137902       0.727602
395  0.006332    1.128021       0.656007

Top 5 rules based on confidence:
                   antecedents      consequents  antecedent support  \
344        (eggs, ground beef)  (mineral water)            0.019997
378        (milk, ground beef)  (mineral water)            0.021997
320   (chocolate, ground beef)  (mineral water)            0.023064
366  (milk, frozen vegetables)  (mineral water)            0.023597
273                     (soup)  (mineral water)            0.050527

     consequent support   support  confidence      lift  leverage  conviction  \
344            0.238368  0.010132    0.506667  2.125563  0.005365    1.543848
378            0.238368  0.011065    0.503030  2.110308  0.005822    1.532552
320            0.238368  0.010932    0.473988  1.988472  0.005434    1.447937
366            0.238368  0.011065    0.468927  1.967236  0.005440    1.434136
273            0.238368  0.023064    0.456464  1.914955  0.011020    1.401255

     zhangs_metric
344       0.540342
378       0.537969
320       0.508837
366       0.503555
273       0.503221

Top 5 rules based on support:
         antecedents      consequents  antecedent support  consequent support  \
274  (mineral water)      (spaghetti)            0.238368            0.174110
275      (spaghetti)  (mineral water)            0.174110            0.238368
84   (mineral water)      (chocolate)            0.238368            0.163845
85       (chocolate)  (mineral water)            0.163845            0.238368
128  (mineral water)           (eggs)            0.238368            0.179709

      support  confidence      lift  leverage  conviction  zhangs_metric
274  0.059725    0.250559  1.439085  0.018223    1.102008       0.400606
275  0.059725    0.343032  1.439085  0.018223    1.159314       0.369437
84   0.052660    0.220917  1.348332  0.013604    1.073256       0.339197
85   0.052660    0.321400  1.348332  0.013604    1.122357       0.308965
128  0.050927    0.213647  1.188845  0.008090    1.043158       0.208562

Most frequent antecedents:
(mineral water)    42
(spaghetti)        36
(chocolate)        31
(milk)             27
(eggs)             24
Name: antecedents, dtype: int64

Most frequent consequents:
(mineral water)    42
(spaghetti)        36
(chocolate)        31
(milk)             27
(eggs)             24
Name: consequents, dtype: int64

Example Rule Interpretation:
If a customer buys ['mineral water'], they are likely to buy ['avocado'] as well.
Confidence: 0.04865771812080537, Lift: 1.4599261744966443

C:\Users\KUSHMA\anaconda3\Lib\site-packages\pandas\core\dtypes\cast.py:1641: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])

In [11]:
# Display the rules
print("Top 5 rules based on lift:")
print(rules.nlargest(5, 'lift'))

# Sort the rules by confidence and display the top 5
print("\nTop 5 rules based on confidence:")
print(rules.nlargest(5, 'confidence'))

# Sort the rules by support and display the top 5
print("\nTop 5 rules based on support:")
print(rules.nlargest(5, 'support'))

# Further analysis to interpret the results
# Identify frequent antecedents and consequents
frequent_antecedents = rules['antecedents'].value_counts().head()
frequent_consequents = rules['consequents'].value_counts().head()

print("\nMost frequent antecedents:")
print(frequent_antecedents)

print("\nMost frequent consequents:")
print(frequent_consequents)

# Example of interpreting a rule
example_rule = rules.iloc[0]
antecedents = list(example_rule['antecedents'])
consequents = list(example_rule['consequents'])
confidence = example_rule['confidence']
lift = example_rule['lift']

print(f"\nExample Rule Interpretation:\nIf a customer buys {antecedents}, they are likely to buy {consequents} as well.")
print(f"Confidence: {confidence}, Lift: {lift}")

Top 5 rules based on lift:
                    antecedents                 consequents  \
215             (herb & pepper)               (ground beef)
214               (ground beef)             (herb & pepper)
382  (mineral water, spaghetti)               (ground beef)
387               (ground beef)  (mineral water, spaghetti)
394  (mineral water, spaghetti)                 (olive oil)

     antecedent support  consequent support   support  confidence      lift  \
215            0.049460            0.098254  0.015998    0.323450  3.291994
214            0.098254            0.049460  0.015998    0.162822  3.291994
382            0.059725            0.098254  0.017064    0.285714  2.907928
387            0.098254            0.059725  0.017064    0.173677  2.907928
394            0.059725            0.065858  0.010265    0.171875  2.609786

     leverage  conviction  zhangs_metric
215  0.011138    1.332860       0.732460
214  0.011138    1.135410       0.772094
382  0.011196    1.262445       0.697788
387  0.011196    1.137902       0.727602
394  0.006332    1.128021       0.656007

Top 5 rules based on confidence:
                   antecedents      consequents  antecedent support  \
344        (ground beef, eggs)  (mineral water)            0.019997
377        (milk, ground beef)  (mineral water)            0.021997
320   (ground beef, chocolate)  (mineral water)            0.023064
365  (frozen vegetables, milk)  (mineral water)            0.023597
273                     (soup)  (mineral water)            0.050527

     consequent support   support  confidence      lift  leverage  conviction  \
344            0.238368  0.010132    0.506667  2.125563  0.005365    1.543848
377            0.238368  0.011065    0.503030  2.110308  0.005822    1.532552
320            0.238368  0.010932    0.473988  1.988472  0.005434    1.447937
365            0.238368  0.011065    0.468927  1.967236  0.005440    1.434136
273            0.238368  0.023064    0.456464  1.914955  0.011020    1.401255

     zhangs_metric
344       0.540342
377       0.537969
320       0.508837
365       0.503555
273       0.503221

Top 5 rules based on support:
         antecedents      consequents  antecedent support  consequent support  \
274  (mineral water)      (spaghetti)            0.238368            0.174110
275      (spaghetti)  (mineral water)            0.174110            0.238368
84   (mineral water)      (chocolate)            0.238368            0.163845
85       (chocolate)  (mineral water)            0.163845            0.238368
128  (mineral water)           (eggs)            0.238368            0.179709

      support  confidence      lift  leverage  conviction  zhangs_metric
274  0.059725    0.250559  1.439085  0.018223    1.102008       0.400606
275  0.059725    0.343032  1.439085  0.018223    1.159314       0.369437
84   0.052660    0.220917  1.348332  0.013604    1.073256       0.339197
85   0.052660    0.321400  1.348332  0.013604    1.122357       0.308965
128  0.050927    0.213647  1.188845  0.008090    1.043158       0.208562

Most frequent antecedents:
antecedents
(mineral water)    42
(spaghetti)        36
(chocolate)        31
(milk)             27
(eggs)             24
Name: count, dtype: int64

Most frequent consequents:
consequents
(mineral water)    42
(spaghetti)        36
(chocolate)        31
(milk)             27
(eggs)             24
Name: count, dtype: int64

Example Rule Interpretation:
If a customer buys ['mineral water'], they are likely to buy ['avocado'] as well.
Confidence: 0.04865771812080537, Lift: 1.4599261744966443